export { default as About } from './About'
export {default as Skills} from './Skills'
export {default as Contact} from './Contact'
export { default as Work } from './Work'
export {default as Header} from './Header'
export {default as Footer} from './Footer'
