export { default as About } from './About'
export {default as Plan} from './Plan'
export {default as Testimonials} from './Testimonials'
export { default as Work } from './Work'
export {default as Header} from './Header'
export {default as Footer} from './Footer'
